---
root: true

parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended

plugins:
  - import
  - react
  - react-hooks
  - "@typescript-eslint"

settings:
  react:
    version: "detect"

env:
  browser: true
  es6: true
  jest: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  import/first: error

  no-console: warn
  no-eval: error

  prettier/prettier:
    - error
    - endOfLine: auto
    
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn